SchoolManagement/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
 	path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('',include('mainApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainApp/urls.py
from django.conf.urls import url, include
from mainApp import views

urlpatterns = [
# -----------------  COMMON HTML VIEWS ----------------------

    url(r'^login/$', views.login_page),
    url(r'^logout/$', views.logout),

# --------------  COMMON REST VIEWS ---------------------------

    url(r'api/notices/$',views.NoticesListUser.as_view()),
    url(r'api/notices/(?P<pk>[0-9]+)/$',views.NoticeDetailUser.as_view()),

# ------------------ STUDENT HTML VIEWS ------------------------

    url(r'^student/$', views.student_dashboard),
    url(r'^student/notices/$', views.student_notices_list),
    url(r'^student/notices/(?P<pk>[0-9]+)/$', views.student_notice_details),


# -------------------- STUDENT REST VIEWS ----------------------------

    url(r'api/student/user-detail/$',views.StudentDetailUser.as_view()),
    url(r'api/student/subjects/$',views.SubjectListUser.as_view()),
    url(r'api/student/subjects/(?P<pk>[0-9]+)/$',views.Subject_Topic.as_view()),
    url(r'api/student/subjects/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$',views.Subject_Topic_Notes.as_view()),

# --------------------- STAFF HTML VIEWS -------------------------
    url(r'^staff/$', views.staff_dashboard),
    url(r'^staff/notices/$', views.staff_notices),
    url(r'^staff/notices/(?P<pk>[0-9]+)/$', views.staff_details_notices),
    url(r'^staff/notices/(?P<pk>[0-9]+)/edit$', views.staff_edit_notices),
    url(r'^staff/notices/add/$', views.staff_add_notices),
    url(r'^staff/class-notes/$', views.staff_class_notes),
    url(r'^staff/class-notes/(?P<pk>[0-9]+)/$', views.staff_details_class_notes_topic),
    url(r'^staff/class-notes/showtopic/(?P<pk>[0-9]+)/$', views.staff_details_class_notes),

    url(r'^staff/sessions/$', views.staff_sessions),
    url(r'^staff/classes/$', views.staff_classes),
    url(r'^staff/classes/(?P<pk>[0-9]+)/$', views.staff_details_class),
    url(r'^staff/sections/(?P<pk>[0-9]+)/$', views.staff_details_section),
    url(r'^staff/subjects/$', views.staff_subjects),
    url(r'^staff/students/$', views.staff_students),
    url(r'^staff/students/(?P<pk>[0-9]+)/$', views.staff_details_student),
    url(r'^staff/students/update/(?P<pk>[0-9]+)/$', views.staff_update_student),
    url(r'^staff/teachers/$', views.staff_teachers),
    url(r'^staff/staff-members/$', views.staff_staff_members),
    url(r'^staff/staff-members/(?P<pk>[0-9]+)/$', views.staff_staff_member_detail),

# --------------------- STAFF REST VIEWS ---------------------------
    url(r'api/notices/(?P<pk>[0-9]+)/$', views.NoticeDetail.as_view()),
    url(r'api/notices/$', views.NoticesList.as_view()),
    url(r'api/students/$', views.StudentsList.as_view()),
    url(r'api/students/(?P<pk>[0-9]+)/$', views.StudentDetails.as_view(), name="student-detail"),
    #-----new----
    url(r'api/teacher/notes/$',views.ClassNoteListUser.as_view()),



]

mainApp/models.py
from django.db import models
from django.contrib.auth.models import User
from bs4 import BeautifulSoup
# Models Definition:


def get_current_session():
    return Session.objects.filter(is_current = True)[0]

class Student(models.Model):
    auth_user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='student')
    admission_number = models.CharField(max_length=50, unique=True)
    year_of_admission = models.CharField(blank=True, max_length=8,default="")
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64, blank=True)
    gender = models.CharField(blank=True, max_length=16,default="")
    adhaar_number = models.CharField(blank=True,max_length=64,default="")
    fathers_first_name = models.CharField(max_length=64, blank=True)
    fathers_last_name = models.CharField(max_length=64, blank=True)
    mothers_first_name = models.CharField(max_length=64, blank=True)
    mothers_last_name = models.CharField(max_length=64, blank=True)
    gaurdians_first_name = models.CharField(max_length=64, blank=True)
    gaurdians_last_name = models.CharField(max_length=64, blank=True)
    profile_pic = models.ImageField(upload_to='students/profilePics/', blank=True, null=True)
    contact_number = models.CharField(max_length=16, blank=True)
    emergency_contact_number = models.CharField(max_length=16, blank=True)
    blood_group = models.CharField(max_length=16, blank=True)
    medical_problems = models.TextField(blank=True)
    address = models.TextField(blank=True)

    def __str__(self):
        return str(self.auth_user.username)

    @property
    def current_class(self):
        current_session = get_current_session()
        return StudentClass.objects.get(student = self, session = current_session).class_w_section._class
    

    @property
    def current_section(self):
        current_session = get_current_session()
        return StudentClass.objects.get(student = self, session = current_session).class_w_section.section
    

class Staff(models.Model):
    TYPE_TEACHER = "Teacher"
    TYPE_STAFF = "Staff"
    TYPE_CHOICES = ((TYPE_TEACHER,TYPE_TEACHER),(TYPE_STAFF,TYPE_STAFF),)

    auth_user = models.OneToOneField(User, on_delete=models.CASCADE, related_name = 'staff')
    profile_pic = models.ImageField(upload_to='staff/profilePics/', blank=True, null=True)
    staff_type = models.CharField(choices=TYPE_CHOICES, max_length=50)
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64, blank=True)
    gender = models.CharField(max_length=64)
    contact_number = models.CharField(max_length=16, blank=True)
    address = models.TextField(blank=True)
    blood_group = models.CharField(max_length=16, blank=True)

    def __str__(self):
        return str(self.auth_user.username)


class Class(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return str(self.name)

class Class_w_Section(models.Model):
    """Class with Section """
    _class = models.ForeignKey("mainApp.Class",  on_delete=models.CASCADE)
    section = models.CharField(max_length=8)

    def __str__(self):
        return str(self._class) + " [" + self.section + "]" 

    @property
    def class_teacher(self):
        try:
            teacher = TeacherClass.objects.filter(session = get_current_session(), class_w_section = self, is_class_teacher = True)[0].teacher
        except:
            return None
        return teacher
            

class Session(models.Model):
    period = models.CharField(max_length=64)
    is_current = models.BooleanField(default = False)

    # def save()
    # TODO: if no other session exists:
    #           Mark current session as is_current = True

    def __str__(self):
        return self.period
    

class StudentClass(models.Model):
    session = models.ForeignKey("mainApp.Session", on_delete=models.CASCADE)
    student = models.ForeignKey("mainApp.Student", on_delete=models.CASCADE)
    class_w_section = models.ForeignKey("mainApp.Class_w_Section",  on_delete=models.CASCADE)
    roll_number = models.PositiveIntegerField(blank=True)

    def __str__(self):
        return str(self.student) + " " + str(self.class_w_section) + " " + str(self.session) 

    # TODO: if session and student with same details already exists then update instead of adding or raise exception
    

class TeacherClass(models.Model):
    session = models.ForeignKey("mainApp.Session", on_delete=models.CASCADE)
    teacher = models.ForeignKey("mainApp.Staff", on_delete=models.CASCADE)
    subject = models.ForeignKey("mainApp.Subject", on_delete=models.CASCADE)
    class_w_section = models.ForeignKey("mainApp.Class_w_Section",  on_delete=models.CASCADE)
    is_class_teacher = models.BooleanField(default=False)
    
    def __str__(self):
        return str(self.teacher) + " teaching  " + str(self.subject) + " to Class " + str(self.class_w_section) + " Session: "+str(self.session) 


class Subject(models.Model):
    subject_code = models.CharField(max_length=64, unique=True)
    name = models.CharField(max_length=128)
    _class = models.ForeignKey("mainApp.Class",  on_delete=models.CASCADE)

    def __str__(self):
        return self.subject_code + " : "+  self.name 

    @property
    def topic_count(self):
        return self.classnotestopic_set.all().count()
    

class ClassNotesTopic(models.Model):
    subject = models.ForeignKey("mainApp.Subject", on_delete=models.PROTECT)
    name = models.CharField(default="Topic", max_length=128)
    description = models.TextField(default="", null=True, blank=True)
    updated_by = models.ForeignKey(User, on_delete = models.PROTECT)
    updated_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.subject) + ": " + self.name

    @property
    def notes_count(self):
        return self.classnote_set.all().count()
    
 
def notes_directory_path(note, filename):
    return 'class_notes/topic_{0}/{1}'.format(note.topic.id, filename)

class ClassNote(models.Model):
    topic = models.ForeignKey("mainApp.ClassNotesTopic", on_delete=models.PROTECT)
    title = models.CharField(default="", max_length=256,null=True, blank=True)
    description = models.TextField(default="",null=True, blank=True)
    file = models.FileField(upload_to= notes_directory_path,blank=True,null=True)
    updated_by = models.ForeignKey(User, on_delete = models.PROTECT)
    updated_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.topic) + ' ' + self.title

class Notice(models.Model):
    TYPE_FEES = 'fees'
    TYPE_IMPORTANT = 'important'
    TYPE_GENERAL = 'general'
    TYPE_CHOICES = ((TYPE_FEES,TYPE_FEES),(TYPE_IMPORTANT,TYPE_IMPORTANT),(TYPE_GENERAL,TYPE_GENERAL),)
    
    title = models.CharField(max_length=128)
    body = models.TextField()
    type_notice = models.CharField(choices=TYPE_CHOICES, max_length=32)
    posted_by = models.ForeignKey("mainApp.Staff", on_delete=models.CASCADE)
    publish_on = models.DateTimeField(auto_now=False, auto_now_add=False)
    description_slug = models.TextField(null = True, blank=True, default = "")

    def save(self, *args, **kwargs):
        soup = BeautifulSoup(self.body, 'html.parser')
        texts = soup.findAll(text=True)
        self.description_slug = u" ".join(t.strip() for t in texts)
        super(Notice, self).save( *args, **kwargs)
    
    def __str__(self):
        return "(" + self.type_notice + ") " + self.title 




class UserNotice(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notice = models.ForeignKey("mainApp.Notice", on_delete=models.CASCADE)

    def __str__(self):
        return "User: "+ str(self.user) + " Notice: " + str(self.notice) 



    

mainApp/forms.py
from .models import *
from django import forms

class StaffMemberForm(forms.ModelForm):
	class Meta:
		model = Staff
		exclude = ['auth_user',]

mainApp/templates/staff/add-notices.html
{% extends 'staff/base.html' %}
{% load static %}

{% block title %} NOTICES | Ankur School  {% endblock title %}

{% block headScripts %}
    <link href="{% static 'plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css'%}" rel="stylesheet" />

{% endblock headScripts %}
{% block content %}
<div class="block-header">
<ol class="breadcrumb ">
    <li><a href="/staff/"><i class="material-icons">home</i> Home</a></li>
    <li><a href="/staff/notices/"><i class="material-icons">event_note</i> Notices</a></li>
    <li><a href="/staff/notices/add"><i class="material-icons">add</i> Add</a></li>
</ol>
</div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Notify Users
                </h2>
                <div class='header-dropdown'>
                  </div>
            </div>

            <div class="body">
            {% if message %}
                <div class="alert alert-{{msgType}}">
                    {{message}}
                </div>
            {% endif %}
            <form method="POST">
            {% csrf_token %}
            <div class='row clearfix'>
                <div class="col-sm-12">
                    <b>Title:</b>
                    <div class="input-group">
                        <div class="form-line">
                            <input type="text" name='title' class="form-control" placeholder="Notice Title" required>
                        </div>
                    </div>
                </div>
                
                <div class="col-sm-12">
                    <b>Users:</b>
                        <select name="users" class="form-control show-tick ">
                            <option value="ALL_USERS">All Users</option>
                            <option value="ALL_TEACHERS">All Teachers</option>
                            <option value="ALL_STUDENTS">All Students</option>
                            <option value="ALL_STAFF_MEMBERS">All Staff Members</option>
                            <option value="SELECTED_USERS">Selected Users</option>
                        </select>
                </div>
                 
                <div class='col-sm-6'>
                    <b>Type: </b> <br>
                    <div style="padding-top: 12px;">
                        <input name="type" type="radio" id="general" value="general" class="radio-col-teal" checked>
                        <label for="general">GENERAL</label>

                        <input name="type" type="radio" id="important" value="important" class="radio-col-red" >
                        <label for="important">IMPORTANT</label>

                        <input name="type" type="radio" id="fees" value="fees" class="radio-col-purple" >
                        <label for="fees">FEES</label>
                    </div>
                </div>
                <div class="col-sm-6">
                    <b>Publish on:</b>
                       <div class="input-group">
                            <div class="form-line">
                                <input required type="text" name='time' class="datetimepicker form-control" placeholder="Please choose date & time...">
                            </div>
                        </div> 
                </div>
                <div class='col-sm-12'>
                    <b>Content: </b>
                    <textarea id='content' required name='content'>
                    </textarea>
                </div>
                 <div class='col-sm-6'>
                    <button type="submit" class="btn bg-teal btn-block btn-lg waves-effect">NOTIFY !</button>                    
                </div>
            </div>
            
            </form>
            
                
                
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="customFiltersModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="customFiltersModalLabel">Custom Filters</h4>
            </div>
            <div class="modal-body">
                
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link waves-effect">DONE</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

{% block footerScripts %}
<script src="{% static 'plugins/momentjs/moment.js'%}"></script>
<script src="{% static 'plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js'%}"></script>


<script>
var selectedPKs=[];

$(document).ready(function(){
    $('.datetimepicker').bootstrapMaterialDatePicker({
            format: 'YYYY-MM-DD HH:MM',
            clearButton: true,
            weekStart: 1
        });

    tinymce.init({
    selector: 'textarea',  // change this value according to your HTML
    plugins : 'advlist autolink link image lists charmap print preview code imagetools media table',
    min_height: 400,
    paste_data_images: true

    });

    
});

</script>
{% endblock footerScripts %}

mainApp/templates/staff/dashboard.html
{% extends 'staff/base.html' %}
{% block title %} Dashboard | Staff members  {% endblock title %}

{% block content %}

{% endblock content %}

mainApp/templates/staff/details-classes.html
{% extends 'staff/base.html' %}
{% block title %} Classes | Ankur School  {% endblock title %}

{% block content %}

<div class="block-header">
    <h2>CLASSES</h2>
</div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                   Class {{class.name}}
                </h2>

            </div>

            <div class="body">
                
                <div class="card">
                    <div class="header bg-blue-grey">
                        <h2>
                            SECTIONS
                        </h2> 
                        <div class='header-dropdown'>
                            <button type="button" class="btn btn-default waves-effect" onclick='window.location.href="add";'>ADD SECTION +</button>
                        </div>
                    </div>
                   <div class="body table-responsive">
                            <table class="table table-condensed table-hover">
                                <thead>
                                    <tr>
                                        <th>SECTION NAME</th>
                                        <th>CLASS TEACHER</th>
                                        <th>ACTIONS</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for section in class.sections %}
                                    <tr>
                                        <td>{{section.section}}</td>
                                        <td>{% if section.class_teacher %}
                                            
                                        <a href='#'>{{section.class_teacher.first_name}} {{section.class_teacher.last_name}}</a>
                                        {% else %}
                                        NONE
                                        {% endif %}
                                        </td>
                                        <td>
                                            <i class="material-icons" style="cursor:pointer;" onclick="window.location.href='/staff/sections/{{section.pk}}/';">info_outline</i>
                                            <span>&nbsp;</span>
                                            <i class="material-icons">create</i>
                                            <span>&nbsp;</span>
                                            <i class="material-icons">clear</i>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                 
                                </tbody>
                            </table>
                        </div>
                </div>
                
            
                <div class="card">
                    <div class="header bg-blue-grey">
                        <h2>
                            SUBJECTS
                        </h2> 
                        <div class='header-dropdown'>
                            <button type="button" class="btn btn-default waves-effect" onclick='window.location.href="add";'>ADD SUBJECT +</button>
                        </div>
                    </div>
                   <div class="body table-responsive">
                            <table class="table table-condensed">
                                <thead>
                                    <tr>
                                        <th>SUBJECT CODE</th>
                                        <th>NAME</th>
                                        <th >CLASS NOTES TOPICS</th>
                                        <th>ACTIONS</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for subject in class.subjects %}
                                    <tr>
                                        <th scope="row">{{subject.subject_code}}</th>
                                        <td>{{subject.name}}</td>
                                        <td ><span class="badge bg-green">{{subject.topic_count}}</span> 
                                            <span onclick="window.location.href='/staff/class-notes/{{subject.pk}}/'" style="cursor:pointer;"  class="badge bg-blue">View Class Topics</span> </td>
                                        <td>
                                            <i class="material-icons">create</i>
                                            <span>&nbsp;</span>
                                            <i class="material-icons">clear</i>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                </div>
                

                <div class="card">
                    <div class="header bg-blue-grey">
                        <h2>
                            ALL STUDENTS
                        </h2> 
                        <div class='header-dropdown'>
                            <button type="button" class="btn btn-default waves-effect" onclick='window.location.href="add";'>ADD STUDENT +</button>
                        </div>
                    </div>
                   <div class="body table-responsive">
                            <table class="table table-condensed">
                                <thead>
                                    <tr>
                                        <th>SECTION</th>
                                        <th>ROLL NO.</th>
                                        <th>NAME</th>
                                        <th>ACTIONS</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for class_student in class_students %}
                                        
                                    <tr>
                                        <td >{{class_student.class_w_section.section}}</td>
                                        <td>{{class_student.roll_number}}</td>
                                        <td><a href='#'>{{class_student.student.first_name}} {{class_student.student.last_name}}</a></td>
                                        <td>

                                            <i class="material-icons">info_outline</i>
                                            <span>&nbsp;</span>
                                            <i class="material-icons">create</i>
                                            <span>&nbsp;</span>
                                            <i class="material-icons">clear</i>
                                        </td>
                                    </tr>
                                    
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                </div>
                

            </div>
        </div>
    </div>
</div>
{% endblock content %}

mainApp/templates/staff/details-notice.html
{% extends 'staff/base.html' %}
{% load static %}
{% block title %} Notice | Ankur School  {% endblock title %}
{% block headScripts %}
    <link href={% static "plugins/sweetalert/sweetalert.css"%} rel="stylesheet" />

{% endblock headScripts %}
{% block content %}

<div class="block-header">

<ol class="breadcrumb ">
    <li><a href="/staff/"><i class="material-icons">home</i> Home</a></li>
    <li><a href="/staff/notices/"><i class="material-icons">event_note</i> Notices</a></li>
    <li><a href="#">{{notice.title}}</a></li>
</ol>

</div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header bg-{% if notice.type_notice == "important" %}red{% elif notice.type_notice == "fees" %}purple{% elif notice.type_notice == "general" %}teal{% endif %}">
                <h2>
                   {{notice.title}}
                </h2>

                <div class='header-dropdown'>
                  <button type="button" class="btn btn-success waves-effect">View Users </button>
                  <button type="button" class="btn btn-info waves-effect" onclick="window.location.href='edit';">Edit </button>
                  <button type="button" class="btn btn-default waves-effect" onclick="showConfirmMessage();" >Delete </button>
                </div>

            </div>

            <div class="body">
            {% autoescape off %}
                     {{ notice.body }}
            {% endautoescape %}
                
                
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block footerScripts %}

<script src="{% static 'plugins/sweetalert/sweetalert.min.js'%}"></script>

<script>
function showConfirmMessage() {
    swal({
        title: "Are you sure?",
        text: "You will not be able to recover this!",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Yes, delete it!",
        closeOnConfirm: false
    }, function () {

        swal("Deleted!", "Notice has been deleted.", "success");
    });
}
</script>
{% endblock footerScripts %}

mainApp/templates/staff/list-class-notes.html
{% extends 'staff/base.html' %}
{% block title %} Class Notes | Ankur School  {% endblock title %}

{% block content %}

<div class="block-header">
    <h2>SUBJECTS</h2>
</div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Choose Subject
                </h2>
                <div class='header-dropdown'>
                </div>
            </div>

            <div class="body">
                {% for class in classes %}
                    
               <div class="card">
                    <div class="header bg-blue-grey">
                        <h2>
                            Class {{class.name}}
                        </h2> 
                        <div class='header-dropdown'>
                        </div>
                    </div>
                   <div class="body table-responsive">
                            <table class="table table-condensed table-hover">
                                <thead>
                                    <tr>
                                        <th>SUBJECT CODE</th>
                                        <th>NAME</th>
                                        <th>TOPICS</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for subject in class.subject_set.all %}
                                        
                                    <tr style="cursor:pointer;" onclick='window.location.href="{{subject.pk}}";'>
                                        <th scope="row">{{subject.subject_code}}</th>
                                        <td>{{subject.name}}</td>
                                        <td><span class="badge bg-green">{{subject.topic_count}}</span></td>
                                      
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                </div>

               
                {% endfor %}
                

            </div>
        </div>
    </div>
</div>
{% endblock content %}

mainApp/templates/staff/list-classes.html
{% extends 'staff/base.html' %}
{% block title %} Classes | Ankur School  {% endblock title %}

{% block content %}

<div class="block-header">
    <h2>CLASSES</h2>
</div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Manage Classes
                </h2>
                <div class='header-dropdown'>
                  <button type="button" class="btn btn-success waves-effect" onclick='window.location.href="add";'>CREATE +</button>
                </div>
            </div>

            <div class="body">
            {% for class in classes %}
               <div class="card flex-33" onclick="window.location.href='{{class.id}}';">
                    <div class="header bg-blue-grey">
                        <h2>
                            {{class.name}}
                        </h2> 
                    </div>
                    <div class="body">
                        <ul class="list-group">
                            <li class="list-group-item">Sections <span class="badge bg-pink">{{class.section_count}}</span></li>
                            <li class="list-group-item">Subjects <span class="badge bg-cyan">{{class.subject_count}}</span></li>
                        </ul>
                    </div>
                </div>
            {% endfor %}

                

            </div>
        </div>
    </div>
</div>
{% endblock content %}